package Dal;
// Generated 24-dec-2014 14:28:54 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TblProduct generated by hbm2java
 */
public class TblProduct  implements java.io.Serializable {


     private Integer id;
     private TblCategory tblCategory;
     private String name;
     private double prijs;
     private Set tblCartitems = new HashSet(0);

    public TblProduct() {
    }

	
    public TblProduct(int id ,TblCategory tblCategory, String name, double prijs) {
        this.id = id;
        this.tblCategory = tblCategory;
        this.name = name;
        this.prijs = prijs;
    }
    
    public TblProduct(int id ,TblCategory tblCategory, String name, double prijs, Set tblCartitems) {
       this.id=id;
       this.tblCategory = tblCategory;
       this.name = name;
       this.prijs = prijs;
       this.tblCartitems = tblCartitems;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public TblCategory getTblCategory() {
        return this.tblCategory;
    }
    
    public void setTblCategory(TblCategory tblCategory) {
        this.tblCategory = tblCategory;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public double getPrijs() {
        return this.prijs;
    }
    
    public void setPrijs(double prijs) {
        this.prijs = prijs;
    }
    public Set getTblCartitems() {
        return this.tblCartitems;
    }
    
    public void setTblCartitems(Set tblCartitems) {
        this.tblCartitems = tblCartitems;
    }

    @Override
    public String toString() {
        return  name + " €" + prijs ;
    }




}


