/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProductAdmin;

import BO.Category;
import BO.Product;
import Services.CategoryService;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author huang
 */
public class ProductUpdate extends javax.swing.JPanel {

    /**
     * Creates new form ProductUpdate
     */
    public ProductUpdate(Product product)
    {
        initComponents();
        _product = product;
        
       ArrayList<Category> list = CategoryService.selectAll();
     
       for(Category category:list)
       {
           jComboBox.addItem(category.getName());           
       }
       Category category = CategoryService.selectOne(_product.getCategoryid());
       jComboBox.setSelectedItem(category.getName());         
          
      
        txtNaam.setText(_product.getName());
        txtPrijs.setText(Double.toString(_product.getPrijs()));
            
        
       final int option = JOptionPane.showConfirmDialog(null, this, "", JOptionPane.OK_CANCEL_OPTION);    
        if (!(txtNaam.getText().equals("") || txtPrijs.getText().equals("")))
        {
            if (option == JOptionPane.OK_OPTION) 
            {
                _product = new Product();

                _product.setName(txtNaam.getText());
                _product.setPrijs(Double.parseDouble(txtPrijs.getText()));

                Category ob = (Category) jComboBox.getSelectedItem();

                _product.setCategoryid(ob.getId());
            }
            else if (option == JOptionPane.CANCEL_OPTION)
            {
                JFrameProduct jframeproduct = new JFrameProduct();
            }
        }
        else
        {
            JOptionPane.showMessageDialog(jComboBox, "update failed");
        }
    }

    private Product _product;
    
    public Product getProduct()
    {        
        return _product;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNaam = new javax.swing.JTextField();
        txtPrijs = new javax.swing.JTextField();
        jComboBox = new javax.swing.JComboBox();

        jLabel1.setText("naam");

        jLabel2.setText("prijs");

        jLabel3.setText("category");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtNaam)
                        .addComponent(txtPrijs, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                    .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(209, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNaam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPrijs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(129, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtNaam;
    private javax.swing.JTextField txtPrijs;
    // End of variables declaration//GEN-END:variables
}
