package Dal;
// Generated 24-dec-2014 14:28:54 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TblCategory generated by hbm2java
 */
public class TblCategory  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set tblProducts = new HashSet(0);

    public TblCategory() {
    }

	
    public TblCategory(String name) {
        this.name = name;
    }
    public TblCategory(String name, Set tblProducts) {
       this.name = name;
       this.tblProducts = tblProducts;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getTblProducts() {
        return this.tblProducts;
    }
    
    public void setTblProducts(Set tblProducts) {
        this.tblProducts = tblProducts;
    }




}


