package Dal;
// Generated 24-dec-2014 14:28:54 by Hibernate Tools 4.3.1

import static com.sun.org.apache.xerces.internal.util.FeatureState.is;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;
import org.hibernate.Query;




/**
 * TblCartitem generated by hbm2java
 */
public class TblCartitem  implements java.io.Serializable {

     
     private Integer id;
     private TblProduct tblProduct;
     private int quantity;

    public TblCartitem() 
    {
        
    }

    public TblCartitem(TblProduct tblProduct) 
    {
       this.tblProduct = tblProduct;
       this.quantity = getQuantity();
    }
     
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public TblProduct getTblProduct() {
        return this.tblProduct;
    }
    
    public void setTblProduct(TblProduct tblProduct) {
        this.tblProduct = tblProduct;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    
    public void addQuantity(int quantity)
    {
        this.quantity += quantity;
    }
    
    public static TblCartitem findOne(int id , List<TblCartitem> list)
    {
        TblCartitem item;
       
        Iterator ite = list.iterator();
        while(ite.hasNext())
        {
            return item = list.stream().filter(p -> p.getTblProduct().getId() == id).findFirst().get(); 
        }
       
        return null;
        
    }
   

    @Override
    public String toString() {
        return  tblProduct + "   aantal= " + quantity ;
    }

   




}


