/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CategoryAdmin;

import BO.Category;
import BO.Product;
import ProductAdmin.JFrameProduct;
import javax.swing.JOptionPane;

/**
 *
 * @author huang
 */
public class CategoryUpdate extends javax.swing.JPanel {

    /**
     * Creates new form CategoryUpdate
     */
    public CategoryUpdate(Category category)
    {
        initComponents();
        _category = category;
        
       txtNaam.setText(_category.getName());
        
       final int option = JOptionPane.showConfirmDialog(null, this, "", JOptionPane.OK_CANCEL_OPTION);    
       
       if(option == JOptionPane.OK_OPTION)
       {
        _category = new Category();
        
        _category.setName(txtNaam.getText());
      
       }
       
       else if(option == JOptionPane.CANCEL_OPTION)
       {
           JFrameCategory jframecategory = new JFrameCategory();
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNaam = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jLabel1.setText("naam");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtNaam)
                .addGap(196, 196, 196))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNaam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(225, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    private Category _category;
    public Category getCategory()
    {
        return _category;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtNaam;
    // End of variables declaration//GEN-END:variables
}
